### PR TITLE
Merge scraper commands and models

### PR DESCRIPTION
**Pull request by sahilchinoy**
- Add two scraping commands: `scrapecalaccesscandidates` and `scrapecalaccesspropositions`
- Add scraped models: `ScrapedCandidate`, `ScrapedCandidateCommittee`, `CandidateScrapedElection`, `ScrapedProposition`, `ScrapedPropositionCommittee`, `ScrapedPropositionElection`
- Add clean models: `Proposition`, `PropositionCommittee`, `Election`
- Add SQL to populate those models

### CODE REVIEW

**Comment by palewire** [comment]
I might be missing it, but is the ``update_cache`` option on the base ScrapeCommand necessary? I don't see it in the base arguments list, so it might not be surfaced to users.

**Comment by palewire** [comment]
Here's a reminder for later: Let's time how long this takes to run to see if we want to include it in our daily cron.

**Comment by sahilchinoy** [comment]
@palewire Hm, I see the `--cache-only` option being stored in the `update_cache` variable. Does it need to go somewhere besides the `add_arguments` function of the base command?

Also, I'm pretty sure the answer to the timing question is "too long," especially now that we're scraping candidate committees, but I'll try to come up with a more quantitative answer.

**Comment by palewire** [comment]
Got it. I'm just blind plus I forgot about code that wrote myself. Sad state of affairs over here.

**Pull request merged**
